


const routes = {
    dashboard :[
        {
        path:'/',
        element:"Ecommerce",
        exact:true,
        key:'ecommerce'
        },
        {
        path:'/ecommerce',
        element:"Ecommerce",
        exact:true,
        key:'ecommerce'
        }
    ],
    pages:[
        {
            path:'/orders',
            element:'Orders',
            key:'orders',
            exact:true
        },
        {
            path:'/employees',
            element:'Employees',
            key:'employees',
            exact:true
        },
        {
            path:'/customers',
            element:'Customers',
            key:'customers',
            exact:true
        }
    ],
    apps:[
        {
            path:'/kanban',
            element:'Kanban',
            exact:true,
            key:'kanab'
        },
        {
            path:'/editor',
            element:'Editor',
            exact:true,
            key:'editor'
        },
        {
            path:'/calendar',
            element:'Calendar',
            exact:true,
            key:'calendar'
        },
        {
            path:'/color-picker',
            element:'Color-picker',
            exact:true,
            key:'color-picker'
        },
    ],

    charts:[
        {
            path:'/line',
            element:'Line',
            key:'line',
            exact:true
        },
        {
            path:'/area',
            element:'Area',
            key:'area',
            exact:true
        },
        {
            path:'/bar',
            element:'bar',
            key:'bar',
            exact:true
        },
        {
            path:'/pie',
            element:'Pie',
            key:'pie',
            exact:true
        },
        {
            path:'/financial',
            element:'Financial',
            key:'financial',
            exact:true
        },
        {
            path:'/color-mapping',
            element:'ColorMapping',
            key:'color-mapping',
            exact:true
        },
        {
            path:'/pyramid',
            element:'Pyramid',
            key:'pyramid',
            exact:true
        },
        {
            path:'/stacked',
            element:'Stacked',
            key:'stacked',
            exact:true
        }
    ]


}